name: 

on:
  push:
    branches: []
  pull_request:
    branches: []

jobs:
  :
    runs-on: 

    steps:
      - name: Checkout repository

      - name: Setup Node

      - name: Install dependencies

      - name: Run tests